// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/text-filter.proto

package blogArch

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TextFilterServiceClient is the client API for TextFilterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextFilterServiceClient interface {
	CreateFilterOutput(ctx context.Context, in *FilterInput, opts ...grpc.CallOption) (*FilterOutput, error)
}

type textFilterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextFilterServiceClient(cc grpc.ClientConnInterface) TextFilterServiceClient {
	return &textFilterServiceClient{cc}
}

func (c *textFilterServiceClient) CreateFilterOutput(ctx context.Context, in *FilterInput, opts ...grpc.CallOption) (*FilterOutput, error) {
	out := new(FilterOutput)
	err := c.cc.Invoke(ctx, "/proto.textFilterService/CreateFilterOutput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextFilterServiceServer is the server API for TextFilterService service.
// All implementations must embed UnimplementedTextFilterServiceServer
// for forward compatibility
type TextFilterServiceServer interface {
	CreateFilterOutput(context.Context, *FilterInput) (*FilterOutput, error)
	mustEmbedUnimplementedTextFilterServiceServer()
}

// UnimplementedTextFilterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTextFilterServiceServer struct {
}

func (UnimplementedTextFilterServiceServer) CreateFilterOutput(context.Context, *FilterInput) (*FilterOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFilterOutput not implemented")
}
func (UnimplementedTextFilterServiceServer) mustEmbedUnimplementedTextFilterServiceServer() {}

// UnsafeTextFilterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextFilterServiceServer will
// result in compilation errors.
type UnsafeTextFilterServiceServer interface {
	mustEmbedUnimplementedTextFilterServiceServer()
}

func RegisterTextFilterServiceServer(s grpc.ServiceRegistrar, srv TextFilterServiceServer) {
	s.RegisterService(&TextFilterService_ServiceDesc, srv)
}

func _TextFilterService_CreateFilterOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextFilterServiceServer).CreateFilterOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.textFilterService/CreateFilterOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextFilterServiceServer).CreateFilterOutput(ctx, req.(*FilterInput))
	}
	return interceptor(ctx, in, info, handler)
}

// TextFilterService_ServiceDesc is the grpc.ServiceDesc for TextFilterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextFilterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.textFilterService",
	HandlerType: (*TextFilterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFilterOutput",
			Handler:    _TextFilterService_CreateFilterOutput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/text-filter.proto",
}
