// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/text-filter.proto

package blogArch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *FilterOutput) Reset() {
	*x = FilterOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_text_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterOutput) ProtoMessage() {}

func (x *FilterOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_text_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterOutput.ProtoReflect.Descriptor instead.
func (*FilterOutput) Descriptor() ([]byte, []int) {
	return file_proto_text_filter_proto_rawDescGZIP(), []int{0}
}

func (x *FilterOutput) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type FilterInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *FilterInput) Reset() {
	*x = FilterInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_text_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterInput) ProtoMessage() {}

func (x *FilterInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_text_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterInput.ProtoReflect.Descriptor instead.
func (*FilterInput) Descriptor() ([]byte, []int) {
	return file_proto_text_filter_proto_rawDescGZIP(), []int{1}
}

func (x *FilterInput) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

var File_proto_text_filter_proto protoreflect.FileDescriptor

var file_proto_text_filter_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x2d, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x26, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x23, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x32, 0x54, 0x0a,
	0x11, 0x74, 0x65, 0x78, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3f, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x41, 0x72, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_text_filter_proto_rawDescOnce sync.Once
	file_proto_text_filter_proto_rawDescData = file_proto_text_filter_proto_rawDesc
)

func file_proto_text_filter_proto_rawDescGZIP() []byte {
	file_proto_text_filter_proto_rawDescOnce.Do(func() {
		file_proto_text_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_text_filter_proto_rawDescData)
	})
	return file_proto_text_filter_proto_rawDescData
}

var file_proto_text_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_text_filter_proto_goTypes = []interface{}{
	(*FilterOutput)(nil), // 0: proto.FilterOutput
	(*FilterInput)(nil),  // 1: proto.FilterInput
}
var file_proto_text_filter_proto_depIdxs = []int32{
	1, // 0: proto.textFilterService.CreateFilterOutput:input_type -> proto.FilterInput
	0, // 1: proto.textFilterService.CreateFilterOutput:output_type -> proto.FilterOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_text_filter_proto_init() }
func file_proto_text_filter_proto_init() {
	if File_proto_text_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_text_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_text_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_text_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_text_filter_proto_goTypes,
		DependencyIndexes: file_proto_text_filter_proto_depIdxs,
		MessageInfos:      file_proto_text_filter_proto_msgTypes,
	}.Build()
	File_proto_text_filter_proto = out.File
	file_proto_text_filter_proto_rawDesc = nil
	file_proto_text_filter_proto_goTypes = nil
	file_proto_text_filter_proto_depIdxs = nil
}
